frr defaults traditional
hostname branch-1
log stdout
service integrated-vtysh-config
!
interface lo
 ip address 10.0.0.31/32
!
router bgp 65031
 bgp router-id 10.0.0.31
 no bgp default ipv4-unicast
 no bgp ebgp-requires-policy
 neighbor 172.30.3.2 remote-as 65000
 neighbor 172.30.3.2 description core-1
 !
 address-family ipv4 unicast
  network 10.0.0.31/32
  neighbor 172.30.3.2 activate
 exit-address-family
!
line vty
!
