frr defaults traditional
hostname edge-2
log stdout
service integrated-vtysh-config
!
interface lo
 ip address 10.0.0.12/32
!
router bgp 65012
 bgp router-id 10.0.0.12
 no bgp default ipv4-unicast
 no bgp ebgp-requires-policy
 neighbor 172.30.2.2 remote-as 65000
 neighbor 172.30.2.2 description core-1
 !
 address-family ipv4 unicast
  network 10.0.0.12/32
  neighbor 172.30.2.2 activate
 exit-address-family
!
line vty
!
