"""add operators table and approved_by_operator_id fk

Revision ID: 33112e9b5b1c
Revises: f78faa47f6bd
Create Date: 2026-05-29 18:31:11.649063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33112e9b5b1c'
down_revision: Union[str, Sequence[str], None] = 'f78faa47f6bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operators',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=32), server_default=sa.text("'operator'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operators_display_name'), 'operators', ['display_name'], unique=True)
    op.add_column('recommendations', sa.Column('approved_by_operator_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'recommendations', 'operators', ['approved_by_operator_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recommendations', type_='foreignkey')
    op.drop_column('recommendations', 'approved_by_operator_id')
    op.drop_index(op.f('ix_operators_display_name'), table_name='operators')
    op.drop_table('operators')
    # ### end Alembic commands ###
