"""add operator password hash and sessions

Revision ID: 466922adacef
Revises: 82c1f3c27505
Create Date: 2026-05-30 15:38:44.837664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '466922adacef'
down_revision: Union[str, Sequence[str], None] = '82c1f3c27505'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operator_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('operator_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operator_sessions_operator_id'), 'operator_sessions', ['operator_id'], unique=False)
    op.create_index(op.f('ix_operator_sessions_token'), 'operator_sessions', ['token'], unique=True)
    op.add_column('operators', sa.Column('password_hash', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operators', 'password_hash')
    op.drop_index(op.f('ix_operator_sessions_token'), table_name='operator_sessions')
    op.drop_index(op.f('ix_operator_sessions_operator_id'), table_name='operator_sessions')
    op.drop_table('operator_sessions')
    # ### end Alembic commands ###
