"""add telemetry_observations table

Revision ID: 82c1f3c27505
Revises: 33112e9b5b1c
Create Date: 2026-05-30 15:07:19.183796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '82c1f3c27505'
down_revision: Union[str, Sequence[str], None] = '33112e9b5b1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telemetry_observations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source', sa.String(length=256), nullable=False),
    sa.Column('vendor', sa.String(length=64), nullable=True),
    sa.Column('observation_type', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_incident_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_incident_id'], ['incidents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_observations_created_incident_id'), 'telemetry_observations', ['created_incident_id'], unique=False)
    op.create_index(op.f('ix_telemetry_observations_received_at'), 'telemetry_observations', ['received_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telemetry_observations_received_at'), table_name='telemetry_observations')
    op.drop_index(op.f('ix_telemetry_observations_created_incident_id'), table_name='telemetry_observations')
    op.drop_table('telemetry_observations')
    # ### end Alembic commands ###
