"""add approval columns to recommendations

Revision ID: f78faa47f6bd
Revises: 704b14540105
Create Date: 2026-05-29 17:15:31.952206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f78faa47f6bd'
down_revision: Union[str, Sequence[str], None] = '704b14540105'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendations', sa.Column('approval_status', sa.String(length=32), server_default=sa.text("'pending'"), nullable=False))
    op.add_column('recommendations', sa.Column('approved_by', sa.String(length=128), nullable=True))
    op.add_column('recommendations', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('recommendations', sa.Column('approval_note', sa.Text(), nullable=True))
    op.create_index(op.f('ix_recommendations_approval_status'), 'recommendations', ['approval_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendations_approval_status'), table_name='recommendations')
    op.drop_column('recommendations', 'approval_note')
    op.drop_column('recommendations', 'approved_at')
    op.drop_column('recommendations', 'approved_by')
    op.drop_column('recommendations', 'approval_status')
    # ### end Alembic commands ###
