frr defaults traditional
hostname core-1
log stdout
service integrated-vtysh-config
!
interface lo
 ip address 10.0.0.21/32
!
router bgp 65000
 bgp router-id 10.0.0.21
 no bgp default ipv4-unicast
 no bgp ebgp-requires-policy
 neighbor 172.30.1.1 remote-as 65011
 neighbor 172.30.1.1 description edge-1
 neighbor 172.30.2.1 remote-as 65012
 neighbor 172.30.2.1 description edge-2
 neighbor 172.30.3.1 remote-as 65031
 neighbor 172.30.3.1 description branch-1
 !
 address-family ipv4 unicast
  network 10.0.0.21/32
  neighbor 172.30.1.1 activate
  neighbor 172.30.2.1 activate
  neighbor 172.30.3.1 activate
 exit-address-family
!
line vty
!
