"""Phase 7 deterministic remediation templates.

CRITICAL SAFETY CONTRACT:
- These templates produce TEXT ONLY. Nothing here executes commands, calls
  Ansible, talks to a device, or imports any remote-execution library.
- Every plan is marked `requires_approval=True`.
- Every plan ships with rollback steps + safety notes.
- For risky operations, `proposed_commands` and the Ansible draft both include
  explicit "REQUIRES APPROVED CHANGE WINDOW" markers, and the Ansible draft
  gates the risky task on `when: false` so it cannot run as-is.
"""

from __future__ import annotations

from typing import Any
from uuid import UUID

from app.schemas.remediation import RemediationPlan

PLAN_SOURCE = "phase7_template"

_PLAYBOOK_HEADER = (
    "# DRAFT ONLY - DO NOT RUN WITHOUT REVIEW AND EXPLICIT HUMAN APPROVAL\n"
    "# Generated by NeuroNOC Phase 7 remediation planner for incident {incident_id}.\n"
    "# This file is intentionally non-executable: risky tasks are gated on `when: false`.\n"
    "# Required changes before any run:\n"
    "#   1) An approved change record.\n"
    "#   2) A captured rollback plan.\n"
    "#   3) Operator flips the `when:` guard ONLY after both above are in place.\n"
)


def _confidence_from(report: dict[str, Any]) -> float:
    try:
        return float(report.get("confidence", 0.0) or 0.0)
    except (TypeError, ValueError):
        return 0.0


# ---------- BGP neighbor down ----------


def template_bgp_neighbor_down(
    incident_id: UUID, report: dict[str, Any], _rca: Any
) -> RemediationPlan:
    playbook = _PLAYBOOK_HEADER.format(incident_id=incident_id) + """
- name: BGP neighbor session investigation and soft reset (DRAFT)
  hosts: edge_router
  gather_facts: false
  vars:
    bgp_neighbor_ip: "REPLACE_WITH_NEIGHBOR_IP"
  tasks:
    - name: Pre-check - capture 'show bgp summary' BEFORE
      ansible.builtin.command: "show bgp summary"
      register: bgp_before
      changed_when: false

    - name: Pre-check - capture 'show interface' on the BGP-bearing link
      ansible.builtin.command: "show interface"
      register: iface_before
      changed_when: false

    - name: Soft inbound reset (REQUIRES APPROVED CHANGE WINDOW)
      ansible.builtin.command: "clear ip bgp {{ bgp_neighbor_ip }} soft in"
      # SAFETY GUARD: flip to true ONLY after operator approval and an open change window.
      when: false

    - name: Post-check - capture 'show bgp summary' AFTER
      ansible.builtin.command: "show bgp summary"
      register: bgp_after
      changed_when: false
"""
    return RemediationPlan(
        incident_id=incident_id,
        plan_type="bgp_neighbor_recovery",
        title="BGP neighbor recovery - investigate L1 and soft-reset session (draft)",
        risk="medium",
        requires_approval=True,
        summary=(
            "Draft plan to investigate a flapping BGP session, capture pre/post "
            "evidence, and optionally perform an inbound soft-reset under an "
            "approved change window. No automatic execution."
        ),
        pre_checks=[
            "Capture 'show bgp summary' on both peers and diff against last known-good baseline.",
            "Capture 'show interface <link>' for L1/CRC errors on the BGP-bearing link.",
            "Pull recent syslog around the state change; look for BGP NOTIFY codes.",
            "Confirm an approved change window is open before any state-changing command.",
        ],
        proposed_commands=[
            "show bgp summary",
            "show bgp neighbor <neighbor-ip>",
            "show interface <bgp-bearing-link>",
            "# REQUIRES APPROVAL: clear ip bgp <neighbor-ip> soft in",
        ],
        proposed_ansible_playbook=playbook,
        post_checks=[
            "Re-capture 'show bgp summary' and verify neighbor returns to Established.",
            "Verify advertised-prefix count returns to baseline.",
            "Run end-to-end reachability test for the affected downstream prefixes.",
        ],
        rollback_steps=[
            "A soft-reset is itself non-destructive; if the session does not recover, do nothing further automatically.",
            "If a config change was made (timers, password, prefix-list), revert it from the captured pre-change config.",
            "Escalate to network on-call if Established state is not restored within the change window.",
        ],
        validation_criteria=[
            "Neighbor state Established for at least 5 consecutive minutes.",
            "Received prefix count matches the prior baseline (+/- 5%).",
            "End-to-end reachability test from the affected downstream returns 0% loss.",
        ],
        safety_notes=[
            "DRAFT ONLY - do not run without explicit human approval.",
            "Soft inbound reset can briefly affect traffic; perform only inside the approved window.",
            "Do not perform a hard reset (`clear ip bgp <neighbor>`) as a first step.",
            "Do not reload the router.",
            "Capture and attach pre/post evidence to the incident.",
        ],
        source=PLAN_SOURCE,
        confidence=_confidence_from(report),
    )


# ---------- Interface error spike ----------


def template_interface_errors_spike(
    incident_id: UUID, report: dict[str, Any], _rca: Any
) -> RemediationPlan:
    playbook = _PLAYBOOK_HEADER.format(incident_id=incident_id) + """
- name: Interface error investigation (DRAFT - observational only)
  hosts: affected_device
  gather_facts: false
  tasks:
    - name: Capture interface counters
      ansible.builtin.command: "show interface eth1"
      register: iface_counters
      changed_when: false

    - name: Capture optics diagnostics
      ansible.builtin.command: "show interface eth1 transceiver"
      register: optics
      changed_when: false

    # NO config-change tasks in this template by design.
    # Physical inspection + optic replacement is performed out-of-band under
    # an approved change window after the diagnostics above confirm a fault.
"""
    return RemediationPlan(
        incident_id=incident_id,
        plan_type="interface_physical_investigation",
        title="Interface error spike - diagnose physical layer (draft, no config changes)",
        risk="low",
        requires_approval=True,
        summary=(
            "Draft plan for an interface error / drop spike. First action is "
            "observation, NOT a device config change. Any physical action "
            "(optic clean/reseat/replace) is performed out-of-band under an "
            "approved change window."
        ),
        pre_checks=[
            "Snapshot interface counters (errors, drops, packets) twice 60 seconds apart - delta matters more than absolute.",
            "Capture optic light levels and temperature; compare against vendor spec.",
            "Capture peer-side interface counters; one-sided errors usually point at the local optic.",
            "Confirm no recent re-cabling, optic swap, or topology change happened just before the alarm.",
        ],
        proposed_commands=[
            "show interface <iface>",
            "show interface <iface> transceiver",
            "show interface <iface> counters errors",
            "# No config changes proposed at this stage - physical inspection first.",
        ],
        proposed_ansible_playbook=playbook,
        post_checks=[
            "After physical action: re-capture counters 5 and 30 minutes later; expect error rate at or below baseline.",
            "Compare optic RX power against vendor spec; should now be inside the spec window.",
        ],
        rollback_steps=[
            "No software rollback applicable - the template proposes observation only.",
            "If an optic was physically replaced, the rollback is to re-install the previous optic.",
        ],
        validation_criteria=[
            "Error rate < 50 events/min sustained for 30 minutes.",
            "Optic RX power within vendor spec.",
            "Peer-side counters also show error rate returning to baseline.",
        ],
        safety_notes=[
            "DRAFT ONLY - do not run without explicit human approval.",
            "Do not propose 'shut / no shut' as a first action; it can mask a failing optic.",
            "Do not bring the interface administratively down without traffic-shift planning.",
            "Physical optic / fiber work is outside the scope of this software-only plan.",
        ],
        source=PLAN_SOURCE,
        confidence=_confidence_from(report),
    )


# ---------- Latency / loss ----------


def template_latency_spike(
    incident_id: UUID, report: dict[str, Any], _rca: Any
) -> RemediationPlan:
    playbook = _PLAYBOOK_HEADER.format(incident_id=incident_id) + """
- name: Latency / loss path investigation (DRAFT - observational)
  hosts: slow_hop
  gather_facts: false
  tasks:
    - name: Capture queue / drop counters on the suspect hop
      ansible.builtin.command: "show interface counters queue"
      register: queue_counters
      changed_when: false
    # No QoS / shaper changes in this template; those require their own
    # dedicated plan with explicit approval.
"""
    return RemediationPlan(
        incident_id=incident_id,
        plan_type="latency_loss_investigation",
        title="Latency / loss path investigation (draft)",
        risk="low",
        requires_approval=True,
        summary=(
            "Draft plan to characterise a latency / packet-loss event end-to-end "
            "without changing forwarding state. QoS or path-shift actions are "
            "out of scope and would require a separate approved plan."
        ),
        pre_checks=[
            "Run ping (50+ packets) and traceroute from the affected source to the destination; capture both.",
            "Identify the slowest hop from the traceroute output.",
            "Pull queue / drop counters on the slow hop's upstream and downstream interfaces.",
            "Check for scheduled jobs (backups, replication) that could be saturating the path.",
        ],
        proposed_commands=[
            "ping -c 50 <destination>",
            "traceroute <destination>",
            "show interface counters | include drop|queue",
            "# Top-talker inspection via NetFlow/sFlow if telemetry is available.",
        ],
        proposed_ansible_playbook=playbook,
        post_checks=[
            "Re-run ping after any change; expect RTT within +/- 20% of baseline and loss < 0.5%.",
            "Confirm queue / drop counters stop incrementing on the previously slow hop.",
        ],
        rollback_steps=[
            "No forwarding state is modified by this plan, so no rollback is required for the observational steps.",
            "Any QoS / shaper adjustment proposed as a follow-up must include its own dedicated rollback.",
        ],
        validation_criteria=[
            "RTT within +/- 20% of historical baseline.",
            "Packet loss < 0.5% on a 100-packet probe.",
            "No new drops on the previously slow hop over 15 minutes.",
        ],
        safety_notes=[
            "DRAFT ONLY - do not run without explicit human approval.",
            "Do not reload the slow hop as a first action.",
            "Do not apply experimental ACL drops 'to see what happens'.",
            "Any traffic-shift or QoS change must be its own approved plan.",
        ],
        source=PLAN_SOURCE,
        confidence=_confidence_from(report),
    )


# ---------- Route missing ----------


def template_route_missing(
    incident_id: UUID, report: dict[str, Any], _rca: Any
) -> RemediationPlan:
    playbook = _PLAYBOOK_HEADER.format(incident_id=incident_id) + """
- name: Missing prefix investigation (DRAFT)
  hosts: receiver
  gather_facts: false
  vars:
    prefix: "REPLACE_WITH_PREFIX/MASK"
  tasks:
    - name: Pre-check - confirm prefix is absent on the receiver
      ansible.builtin.command: "show ip route {{ prefix }}"
      register: route_before
      changed_when: false

    # Sender-side prefix-list / route-map edits are an explicit follow-up
    # plan, NOT executed here.

    - name: Post-check - re-query the receiver for the prefix
      ansible.builtin.command: "show ip route {{ prefix }}"
      register: route_after
      changed_when: false
"""
    return RemediationPlan(
        incident_id=incident_id,
        plan_type="route_advertisement_recovery",
        title="Route missing - walk advertisement path and fix policy filter (draft)",
        risk="medium",
        requires_approval=True,
        summary=(
            "Draft plan to walk the BGP advertisement path for a missing prefix, "
            "identify whether the loss is at the sender's outbound policy or the "
            "receiver's inbound policy, and propose a targeted permit-entry fix. "
            "No policy edit is performed automatically."
        ),
        pre_checks=[
            "On receiver: `show ip route <prefix>` to confirm the prefix is absent.",
            "On sender: `show ip bgp <prefix>` to confirm the prefix is still in its local RIB.",
            "On sender: `show bgp neighbors <peer> advertised-routes` to confirm the prefix is being announced.",
            "On both sides: dump the active prefix-list / route-map / community policy that governs this peer.",
            "Diff the active policy against the last known-good revision in version control.",
        ],
        proposed_commands=[
            "show ip route <prefix>",
            "show ip bgp <prefix>",
            "show bgp neighbors <peer-ip> advertised-routes | include <prefix>",
            "show ip prefix-list <policy-name>",
            "# REQUIRES APPROVAL: add explicit `permit <prefix>` entry to the failing prefix-list / route-map.",
        ],
        proposed_ansible_playbook=playbook,
        post_checks=[
            "On receiver: `show ip route <prefix>` returns a valid route via the expected next hop.",
            "On sender: `show bgp neighbors <peer> advertised-routes` includes the prefix.",
            "Run a reachability test from the receiver into the prefix.",
        ],
        rollback_steps=[
            "If a prefix-list `permit` entry was added, remove the same entry by sequence number.",
            "If a route-map was modified, revert from the captured pre-change config.",
            "Restore the prior policy revision from version control if anything else changed.",
        ],
        validation_criteria=[
            "Prefix present in the receiver's RIB with a valid next hop.",
            "Reachability test into the prefix returns 0% loss for 5 consecutive minutes.",
            "No unintended additional prefixes appear in the advertised-routes diff.",
        ],
        safety_notes=[
            "DRAFT ONLY - do not run without explicit human approval.",
            "Do not apply a `permit any` to fix the symptom; add only the specific missing prefix.",
            "Bouncing the BGP session is a separate, riskier plan.",
        ],
        source=PLAN_SOURCE,
        confidence=_confidence_from(report),
    )


# ---------- ACL blocking traffic ----------


def template_acl_blocking_traffic(
    incident_id: UUID, report: dict[str, Any], _rca: Any
) -> RemediationPlan:
    playbook = _PLAYBOOK_HEADER.format(incident_id=incident_id) + """
- name: ACL / policy review (DRAFT)
  hosts: denying_device
  gather_facts: false
  vars:
    acl_name: "REPLACE_WITH_ACL_NAME"
  tasks:
    - name: Pre-check - dump current ACL
      ansible.builtin.command: "show access-list {{ acl_name }}"
      register: acl_before
      changed_when: false

    - name: Pre-check - count deny hits for the affected flow
      ansible.builtin.command: "show access-list {{ acl_name }} | include deny|hits"
      register: deny_hits
      changed_when: false

    # An explicit permit insertion is staged here but gated until approval.
    - name: Insert explicit permit ahead of the deny (REQUIRES APPROVAL)
      ansible.builtin.command: >-
        configure terminal ;
        access-list {{ acl_name }} 15 permit ip <src/mask> <dst/mask> ;
        end
      # SAFETY GUARD: flip to true ONLY after diff review + change record.
      when: false
"""
    return RemediationPlan(
        incident_id=incident_id,
        plan_type="acl_policy_review",
        title="ACL / policy review - diff change and insert targeted permit (draft)",
        risk="medium",
        requires_approval=True,
        summary=(
            "Draft plan to review the recent ACL / policy change, diff against "
            "the previous revision, confirm the denied flow is intended to be "
            "permitted, and propose inserting an explicit permit ahead of the "
            "deny. Policy is not modified automatically."
        ),
        pre_checks=[
            "Pull the change record / commit log for the most recent ACL push on the denying device.",
            "Run `show access-list <name>` and diff against the previous revision.",
            "Inspect deny-hit counters for the affected source/destination pair.",
            "Confirm with the application owner that the affected flow is intended to be permitted.",
            "Run a reachability test from the affected source to confirm the deny location is the suspected hop.",
        ],
        proposed_commands=[
            "show access-list <name>",
            "show access-list <name> | include deny|hits",
            "# REQUIRES APPROVAL: insert explicit permit ahead of the matching deny.",
            "#   access-list <name> <seq> permit ip <src/mask> <dst/mask>",
        ],
        proposed_ansible_playbook=playbook,
        post_checks=[
            "Re-run `show access-list <name>` and confirm the new permit appears at the intended sequence.",
            "Re-run the reachability test - should now succeed.",
            "Confirm deny-hit counters for the previously affected flow stop incrementing.",
        ],
        rollback_steps=[
            "Remove the inserted permit by its sequence number: `no access-list <name> <seq>`.",
            "If anything else was edited, restore the previous policy revision from version control.",
        ],
        validation_criteria=[
            "Affected source -> destination reachability test passes.",
            "Deny-hit counter for the affected flow stops climbing for at least 10 minutes.",
            "No unintended additional flows are now permitted (diff with intended change).",
        ],
        safety_notes=[
            "DRAFT ONLY - do not run without explicit human approval.",
            "Do not add a catch-all `permit ip any any` to mask the symptom.",
            "Do not disable the ACL temporarily as a workaround.",
            "All ACL edits must reference an approved change record.",
        ],
        source=PLAN_SOURCE,
        confidence=_confidence_from(report),
    )


# ---------- Default / unknown ----------


def template_default(
    incident_id: UUID, report: dict[str, Any], _rca: Any
) -> RemediationPlan:
    playbook = _PLAYBOOK_HEADER.format(incident_id=incident_id) + """
- name: Generic incident investigation (DRAFT - observational)
  hosts: tbd
  gather_facts: false
  tasks:
    # No specific remediation template matched. This file intentionally
    # contains NO device-changing tasks. An operator must take over manually.
    - name: Placeholder - operator to define investigation steps
      ansible.builtin.debug:
        msg: "No specific template matched; manual investigation required."
"""
    return RemediationPlan(
        incident_id=incident_id,
        plan_type="generic_investigation",
        title="Manual investigation required - no specific remediation template matched (draft)",
        risk="low",
        requires_approval=True,
        summary=(
            "No specific Phase 7 template matched this incident_type / signal "
            "combination. The plan below contains observational guidance only "
            "and explicitly defers any device-changing action to a human operator."
        ),
        pre_checks=[
            "Collect the full incident timeline, events, and evidence rows.",
            "Identify the affected device(s) and service path(s).",
            "Look for correlated changes (config push, deploy, scheduled job) in the same window.",
        ],
        proposed_commands=[
            "# No specific commands proposed - manual investigation required.",
        ],
        proposed_ansible_playbook=playbook,
        post_checks=[
            "After any operator action: capture before/after state and attach to the incident.",
        ],
        rollback_steps=[
            "Define the rollback per whatever operator action is ultimately taken; no template-defined change.",
        ],
        validation_criteria=[
            "Operator confirms the incident root cause and explicitly closes it.",
        ],
        safety_notes=[
            "DRAFT ONLY - do not run without explicit human approval.",
            "Manual investigation required - no specific template matched this incident type or theme.",
            "No template matched - do not assume any prior plan applies.",
            "All actions require an approved change record and a documented rollback.",
        ],
        source=PLAN_SOURCE,
        confidence=_confidence_from(report),
    )


# ---------- registry + lookup ----------


TEMPLATES = {
    "bgp_neighbor_down": template_bgp_neighbor_down,
    "interface_errors_spike": template_interface_errors_spike,
    "latency_spike": template_latency_spike,
    "route_missing": template_route_missing,
    "acl_blocking_traffic": template_acl_blocking_traffic,
}

# Map correlation themes (from Phase 5) onto the closest specific template.
_THEME_FALLBACK = {
    "routing_failure": template_bgp_neighbor_down,
    "interface_physical_issue": template_interface_errors_spike,
    "latency_or_loss": template_latency_spike,
    "policy_block": template_acl_blocking_traffic,
}


def pick_template(incident_type: str | None, themes: list[str] | None):
    """Pick a template by incident_type first; fall back to correlation theme."""
    if incident_type and incident_type in TEMPLATES:
        return TEMPLATES[incident_type]
    for theme in themes or []:
        if theme in _THEME_FALLBACK:
            return _THEME_FALLBACK[theme]
    return template_default
